# Generated by Django 4.1.2 on 2022-12-07 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mock_company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='drivers_license',
        ),
        migrations.RemoveField(
            model_name='person',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='person',
            name='passport',
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.IntegerField(choices=[(1, 'Passport'), (2, 'Identity Document'), (3, 'Drivers License'), (4, 'Other')])),
                ('file', models.FileField(upload_to='people_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_company.person')),
            ],
        ),
    ]
