# Generated by Django 4.1.2 on 2022-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_company', '0003_remove_persondocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondocument',
            name='document_type',
            field=models.IntegerField(choices=[(0, 'passport'), (1, 'identity_document'), (2, 'drivers_license'), (3, 'extra')], default=3),
        ),
        migrations.AlterField(
            model_name='persondocument',
            name='file',
            field=models.FileField(upload_to='people_files/'),
        ),
    ]
