# Generated by Django 4.0.7 on 2022-10-20 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=128)),
                ('parent_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.box')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.TextField(max_length=280)),
                ('parent_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.box')),
            ],
        ),
    ]
