# Generated by Django 4.0.7 on 2022-10-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_idea_remove_box_parent_box_delete_item_idea_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='Idea_text',
            new_name='idea_text',
        ),
    ]
