# Generated by Django 4.1.2 on 2022-10-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_idea_actionable'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
