# Generated by Django 4.1.2 on 2022-10-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_idea_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='box_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='idea_text',
            new_name='text',
        ),
    ]
