# Generated by Django 4.1.2 on 2022-11-08 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0009_box_created_at_box_owner_box_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='box',
            field=models.ForeignKey(default=1, limit_choices_to={'owner': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='notebook.box'),
        ),
    ]
