# Generated by Django 4.1.2 on 2022-11-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0011_alter_idea_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='box',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='notebook.box'),
        ),
    ]
