# Generated by Django 4.1.2 on 2022-11-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatever', models.TextField(max_length=140)),
                ('parentItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook_2.item')),
            ],
        ),
    ]
