# Generated by Django 4.1.2 on 2022-11-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook_2', '0002_itemversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemVersion',
        ),
    ]
